name: Sync

on:
  push:
  workflow_dispatch:

env:
  PULL_REQUEST: true
  REPOSITORIES: |
    mitsuhide-pub/a
  
  WORKFLOW_FILES: |
    src/python/helloworld.py=/helloworld.py

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set COMMIT_MESSAGE
        run: echo "COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Fetching Local Repository
        uses: actions/checkout@v2

      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          PULL_REQUEST: ${{ env.PULL_REQUEST }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
          RETRY_MODE: true
          
