name: Sync

on:
  push:
  workflow_dispatch:

env:
  PULL_REQUEST: true
  REPOSITORIES: |
    mitsuhide-pub/a
    mitsuhide-pub/b
    mitsuhide-pub/c
    mitsuhide-pub/d
    mitsuhide-pub/e
    mitsuhide-pub/e
    mitsuhide-pub/f
    mitsuhide-pub/g
    mitsuhide-pub/h
    mitsuhide-pub/i
    mitsuhide-pub/j
    mitsuhide-pub/k
    mitsuhide-pub/l
    mitsuhide-pub/m
    mitsuhide-pub/n
    mitsuhide-pub/o
    mitsuhide-pub/p
    mitsuhide-pub/q
    mitsuhide-pub/r
    mitsuhide-pub/s
    mitsuhide-pub/t
    mitsuhide-pub/u
    mitsuhide-pub/v
    mitsuhide-pub/w
    mitsuhide-pub/x
    mitsuhide-pub/y
    mitsuhide-pub/z
    
  
  WORKFLOW_FILES: |
    src/python/helloworld.py=/helloworld.py

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set COMMIT_MESSAGE
        run: echo "COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Fetching Local Repository
        uses: actions/checkout@v2

      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@main
        with:
          PULL_REQUEST: ${{ env.PULL_REQUEST }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.SUZUKIPAT }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
          RETRY_MODE: true
          
